Removing the clone from shellphish/afl-other-arches
shellphish/shellphish-afl pull request #13
Opened 2019-01-26 06:56 UTC by gokulkrishna01

Have removed the clone of AFL-other-arch and instead clones AFL repo and apply patches directly onto it. Also, there is a fix for qemu not working in ubuntu 18.04. @zardus I guess this should do it.

2019-01-26 19:01 UTC, zardus requested changes
Thank you! There are some comments I put. Could you check them out?

2019-01-26 19:01 UTC, zardus commented on setup.py
>          if subprocess.call(['git', 'clone', AFL_UNIX_REPO, AFL_UNIX_INSTALL_PATH]) != 0:
Could you clone this with --depth=0?

2019-01-26 19:01 UTC, zardus commented on patches/other-arch.diff
> +diff -r afl/qemu_mode/build_qemu_support.sh afl-other-arch/qemu_mode/build_qemu_support.sh
This seems to dumplicate `build_qemu_support.sh` above. Could you deduplicate (and check out the comments on the above script as well)?

2019-01-26 19:01 UTC, zardus commented on patches/build_qemu.diff
> +--- qemu_mode/build_qemu_support.sh	2019-01-25 19:26:49.314879371 -0700
Are these invasive changes to the build process necessary? The diff reads like a replacement of the entire build script. Is it a case of the build script continuing to evolve in upstream AFL? Let's try to have minimal necessary changes here.

2019-01-26 23:21 UTC, g0kkk commented
@zardus, have made the necessary changes that were asked

2019-01-27 01:33 UTC, merged

2019-01-27 01:33 UTC, zardus commented
Thank you!